
export default
[ { id: 'url',
    label: 'url',
    type: 'paragraph',
    sample: 'url unknown' },
  { id: 'forks_url',
    label: 'forks_url',
    type: 'paragraph',
    sample: 'forks_url unknown' },
  { id: 'commits_url',
    label: 'commits_url',
    type: 'paragraph',
    sample: 'commits_url unknown' },
  { id: 'id', label: 'id', type: 'paragraph', sample: 'id unknown' },
  { id: 'git_pull_url',
    label: 'git_pull_url',
    type: 'paragraph',
    sample: 'git_pull_url unknown' },
  { id: 'git_push_url',
    label: 'git_push_url',
    type: 'paragraph',
    sample: 'git_push_url unknown' },
  { id: 'html_url',
    label: 'html_url',
    type: 'paragraph',
    sample: 'html_url unknown' },
  { id: 'files',
    label: 'files',
    type: 'paragraph',
    sample: 'files unknown' },
  { id: 'public',
    label: 'public',
    type: 'paragraph',
    sample: 'public unknown' },
  { id: 'created_at',
    label: 'created_at',
    type: 'paragraph',
    sample: 'created_at unknown' },
  { id: 'updated_at',
    label: 'updated_at',
    type: 'paragraph',
    sample: 'updated_at unknown' },
  { id: 'description',
    label: 'description',
    type: 'paragraph',
    sample: 'description unknown' },
  { id: 'comments',
    label: 'comments',
    type: 'paragraph',
    sample: 'comments unknown' },
  { id: 'user',
    label: 'user',
    type: 'paragraph',
    sample: 'user unknown' },
  { id: 'comments_url',
    label: 'comments_url',
    type: 'paragraph',
    sample: 'comments_url unknown' },
  { id: 'owner',
    label: 'owner',
    type: 'paragraph',
    sample: 'owner unknown' },
  { id: 'forks',
    label: 'forks',
    type: 'paragraph',
    sample: 'forks unknown' },
  { id: 'history',
    label: 'history',
    type: 'paragraph',
    sample: 'history unknown' },
  { id: 'truncated',
    label: 'truncated',
    type: 'paragraph',
    sample: 'truncated unknown' } ]
